apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Kafka
  name: ocp-kafka
spec:
  dockerImageRepository: "confluentinc/cp-kafka"
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: confluentinc/cp-kafka:3.3.0
    importPolicy: {}
    name: "3.3.0"
  - annotations: null
    from:
      kind: ImageStreamTag
      name: "3.3.0"
    importPolicy: {}
    name: "3.3.x"
  - annotations: null
    from:
      kind: DockerImage
      name: confluentinc/cp-kafka:latest
    importPolicy: {}
    name: latest
