apiVersion: v1
kind: Template
labels:
  template: kafka-ephemeral-template
message: |-
  The following service(s) have been created in your project: ${KAFKA_SERVICE_NAME}.

   Kafka Port: ${KAFKA_SERVICE_NAME}:9092
metadata:
  annotations:
    description: |-
      A distributed streaming platform, without persistent storage.

      WARNING: Any data stored will be lost upon pod destruction. Only use this template for testing
    openshift.io/display-name: Kafka (Ephemeral)
    tags: database,kafka
    template.openshift.io/documentation-url: https://docs.confluent.io/current/cp-docker-images/docs/intro.html
    template.openshift.io/long-description: This template provides a standalone Kafka
      data stream processing server.  The data is not stored on persistent storage,
      so any restart of the service will result in all data being lost.
    template.openshift.io/provider-display-name: SDP Team
    template.openshift.io/support-url: https://svcmgr.cdc.gov/
  creationTimestamp: null
  name: kafka-ephemeral
objects:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: '${KAFKA_SERVICE_NAME}'
  spec:
    ports:
    - name: kafka
      protocol: TCP
      port: 9092
      targetPort: 9092
    selector:
      name: '${KAFKA_SERVICE_NAME}'
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: '${KAFKA_SERVICE_NAME}'
  spec:
    replicas: 1
    selector:
      name: '${KAFKA_SERVICE_NAME}'
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: '${KAFKA_SERVICE_NAME}'
      spec:
        containers:
        - capabilities: {}
          command:
          - /bin/sh
          - -c
          - unset KAFKA_PORT && /etc/confluent/docker/run
          env:
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "${ZOOKEEPER_CONNECT}"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "PLAINTEXT://${KAFKA_SERVICE_NAME}:9092"
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"
          image: ' '
          imagePullPolicy: IfNotPresent
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: 9092
            timeoutSeconds: 1
          name: kafka
          ports:
          - containerPort: 9092
            protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 9092
            timeoutSeconds: 1
          resources:
            limits:
              memory: ${MEMORY_LIMIT}
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/lib/kafka/data
            name: '${KAFKA_SERVICE_NAME}-data'
          - mountPath: /etc/kafka/secrets
            name: '${KAFKA_SERVICE_NAME}-secrets'
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - emptyDir:
            medium: ''
          name: '${KAFKA_SERVICE_NAME}-data'
        - emptyDir:
            medium: ''
          name: '${KAFKA_SERVICE_NAME}-secrets'
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - kafka
        from:
          kind: ImageStreamTag
          name: ${KAFKA_IMAGE}:${KAFKA_VERSION}
          namespace: ${NAMESPACE}
        lastTriggerImage: ""
      type: ImageChange
    - type: ConfigChange
  status: {}
parameters:
- name: MEMORY_LIMIT
  displayName: Memory Limit
  description: Maximum amount of memory the container can use.
  required: true
  value: 512Mi
- name: NAMESPACE
  displayName: Namespace
  description: The OpenShift Namespace where the ImageStream resides.
  value: openshift
- name: KAFKA_SERVICE_NAME
  displayName: Kafka Service Name
  description: The name of the OpenShift Service exposed for this instance.
  required: true
  value: kafka
- name: KAFKA_IMAGE
  displayName: Kafka Image Name
  description: The name of the Kafka ImageStream to be used.
  required: true
  value: ocp-kafka
- name: KAFKA_VERSION
  displayName: Version of the Kafka Image
  description: Version of the Kafka image to be used (3.3 or latest)
  required: true
  value: "3.3.x"
- name: ZOOKEEPER_CONNECT
  displayName: ZooKeeper Host
  description: Host and port of the ZooKeeper Service that Kafka should used
  required: true
  value: zookeeper:2181
